export const templates = [
  "code-flow",
  "default",
  "process-flow",
  "flowchart",
  "org-chart",
  "network-diagram-dark",
  "decision-flow",
  "pert-light",
  "knowledge-graph",
  "network-diagram-icons",
  "mindmap",
  "playful-mindmap",
  "mindmap-dark",
] as const;
