import { readFileSync } from "fs";
import { join } from "path";

import { compressToEncodedURIComponent } from "lz-string";

/**
 * Templates that proved NON-deterministic in the stability check (force-directed
 * layouts re-randomize node positions every render). These are rendered with
 * FROZEN positions baked into a committed fixture so the geometry is fixed and
 * the visual test deterministically checks RENDERING rather than layout.
 *
 * Each entry has a fixture at ./fixtures/{name}.doc.txt — the full flowchart.fun
 * document string with meta.nodePositions populated. Generated by
 * `generate-frozen-fixtures` (see scripts/), regenerate if a template changes.
 *
 * Populated empirically after the first all-live stability run: these three
 * mindmap templates (force-directed cose layout) failed the same comparison on
 * two consecutive runs; the other 10 — including the two cose network-diagram
 * templates and the ELK stress one — rendered stably and use the live path.
 */
export const FROZEN_TEMPLATES: string[] = [
  "mindmap",
  "playful-mindmap",
  "mindmap-dark",
];

const ORIGIN = process.env.E2E_START_URL || "http://localhost:3000";

/**
 * Build a fullscreen screenshot URL from a committed frozen-document fixture.
 * The /f route decodes the lz-string hash; with meta.nodePositions set, Graph
 * renders a deterministic `preset` layout.
 */
export function frozenScreenshotUrl(name: string): string {
  const doc = readFileSync(
    join(__dirname, "fixtures", `${name}.doc.txt`),
    "utf8"
  );
  return `${ORIGIN}/f?screenshot=true#${compressToEncodedURIComponent(doc)}`;
}
